export const defaultSections=[
 {id:1,section_key:'identification',label:'Identification',sort_order:10,is_visible:1},
 {id:2,section_key:'keyed',label:'Keyed Stem',sort_order:20,is_visible:1},
 {id:3,section_key:'flat',label:'Flat Stem',sort_order:30,is_visible:1},
 {id:4,section_key:'manufacturing',label:'Manufacturing Summary',sort_order:40,is_visible:1}
];
const definitions:Array<[string,string,string]>=[
 ['valve.valve_id','identification','Valve ID'],['valve.valve_brand','identification','Brand'],['valve.valve_size','identification','Size'],['valve.valve_class','identification','Class'],['valve.valve_model_number','identification','Model Number'],['valve.valve_port','identification','Port'],['valve.stem_type','identification','Stem Type'],['valve.description','identification','Description'],
 ['keyed.stem_diameter','keyed','Stem Diameter'],['keyed.stem_height','keyed','Stem Height'],['keyed.key_qty','keyed','Key Quantity'],['keyed.key_width','keyed','Key Width'],['keyed.key_cross','keyed','Key Cross'],['keyed.valve_bhc','keyed','Valve Bolt-hole Circle'],['keyed.valve_hole_dia','keyed','Valve Hole Diameter'],['keyed.valve_hole_qty','keyed','Valve Hole Quantity'],['keyed.valve_start_angle','keyed','Valve Start Angle'],
 ['flat.stem_height','flat','Stem Height'],['flat.flat_width','flat','Flat Width'],['flat.flat_depth','flat','Flat Depth'],['flat.valve_bhc','flat','Valve Bolt-hole Circle'],['flat.valve_hole_dia','flat','Valve Hole Diameter'],['flat.valve_hole_qty','flat','Valve Hole Quantity'],['flat.valve_start_angle','flat','Valve Start Angle'],['flat.packing_flange','flat','Packing Flange'],['flat.packing_flange_width','flat','Packing-flange Width'],['flat.packing_flange_length','flat','Packing-flange Length'],['flat.packing_flange_angle','flat','Packing-flange Angle'],['flat.dia_reduction','flat','Diameter Reduction'],['flat.dia_reduction_value','flat','Diameter-reduction Value'],['flat.stem_thread','flat','Stem Thread'],['flat.stem_thread_dia','flat','Stem-thread Diameter'],['flat.stem_thread_depth','flat','Stem-thread Depth'],['flat.u_bolt','flat','U-bolt'],['flat.u_bolt_valve_width','flat','U-bolt Valve Width'],['flat.u_bolt_valve_length','flat','U-bolt Valve Length'],['flat.valve_pattern_type','flat','Valve Pattern Type'],['flat.valve_grid_x_distance','flat','Grid X Distance'],['flat.valve_grid_y_distance','flat','Grid Y Distance']
];
export const defaultFields=definitions.map(([field_key,section_key,label],index)=>({id:index+1,field_key,section_key,label,sort_order:(index+1)*10,is_visible:1,is_highlighted:0,unit:null as string|null,decimal_places:null as number|null,help_text:null as string|null}));
