export const defaultSections=[
 {id:1,section_key:'identification',label:'Identification',sort_order:10,is_visible:1},
 {id:2,section_key:'keyed',label:'Keyed Stem',sort_order:20,is_visible:1},
 {id:3,section_key:'flat',label:'Flat Stem',sort_order:30,is_visible:1},
 {id:4,section_key:'manufacturing',label:'Configurator & Drawing Summary',sort_order:40,is_visible:1}
];
const definitions:Array<[string,string,string]>=[
 ['valve.valve_id','identification','Valve ID'],['valve.valve_brand','identification','Brand'],['valve.valve_size','identification','Size'],['valve.valve_class','identification','Class'],['valve.valve_model_number','identification','Model Number'],['valve.valve_port','identification','Port'],['valve.stem_type','identification','Stem Type'],['valve.description','identification','Description'],
 ['keyed.stem_diameter','keyed','Stem Diameter'],['keyed.stem_height','keyed','Stem Height'],['keyed.key_qty','keyed','Key Quantity'],['keyed.key_width','keyed','Key Width'],['keyed.key_cross','keyed','Key Cross'],['keyed.valve_bhc','keyed','Valve Bolt-hole Circle'],['keyed.valve_hole_dia','keyed','Valve Hole Diameter'],['keyed.valve_hole_qty','keyed','Valve Hole Quantity'],['keyed.valve_start_angle','keyed','Valve Start Angle'],
 ['flat.stem_height','flat','Stem Height'],['flat.flat_width','flat','Flat Width'],['flat.flat_depth','flat','Flat Depth'],['flat.valve_bhc','flat','Valve Bolt-hole Circle'],['flat.valve_hole_dia','flat','Valve Hole Diameter'],['flat.valve_hole_qty','flat','Valve Hole Quantity'],['flat.valve_start_angle','flat','Valve Start Angle'],['flat.packing_flange','flat','Packing Flange'],['flat.packing_flange_width','flat','Packing-flange Width'],['flat.packing_flange_length','flat','Packing-flange Length'],['flat.packing_flange_angle','flat','Packing-flange Angle'],['flat.dia_reduction','flat','Diameter Reduction'],['flat.dia_reduction_value','flat','Diameter-reduction Value'],['flat.stem_thread','flat','Stem Thread'],['flat.stem_thread_dia','flat','Stem-thread Diameter'],['flat.stem_thread_depth','flat','Stem-thread Depth'],['flat.u_bolt','flat','U-bolt'],['flat.u_bolt_valve_width','flat','U-bolt Valve Width'],['flat.u_bolt_valve_length','flat','U-bolt Valve Length'],['flat.valve_pattern_type','flat','Valve Pattern Type'],['flat.valve_grid_x_distance','flat','Grid X Distance'],['flat.valve_grid_y_distance','flat','Grid Y Distance'],
 ['summary.last_drawing_created','manufacturing','Last Drawing Created'],['summary.last_job','manufacturing','Last Job'],['summary.last_quantity','manufacturing','Last Quantity'],['summary.configuration','manufacturing','Configuration'],['summary.fusion_document','manufacturing','Fusion Document'],['summary.actuator','manufacturing','Actuator'],['summary.total_runs','manufacturing','Configurator Runs']
];
export const defaultFields=definitions.map(([field_key,section_key,label],index)=>({id:index+1,field_key,section_key,label,sort_order:(index+1)*10,is_visible:1,is_highlighted:0,unit:null as string|null,decimal_places:null as number|null,help_text:null as string|null}));

const actuatorColumns=['actuator_id','actuator_name','theme_name','square_size','square_height','sq_rad','d_stem','actuator_hole_dia','actuator_bhc','actuator_hole_qty','actuator_start_angle','bracket_height'];
const bracketColumns=['bracket_id','bracket_code','actuator_1_bhc','actuator_1_hole_dia','actuator_1_hole_qty','actuator_1_start_angle','actuator_2_bhc','actuator_2_hole_dia','actuator_2_hole_qty','actuator_2_start_angle','actuator_3_bhc','actuator_3_hole_dia','actuator_3_hole_qty','actuator_3_start_angle','valve_bhc','valve_hole_dia','valve_hole_qty','valve_start_angle','valve_2_bhc','valve_2_hole_dia','valve_2_hole_qty','valve_2_start_angle','valve_3_bhc','valve_3_hole_dia','valve_3_hole_qty','valve_3_start_angle','bracket_width','bracket_length','bracket_height','actuator_bracket_center_hole','valve_bracket_center_hole','packing_flange','packing_flange_width','packing_flange_length','packing_flange_angle','d_actuator_bracket_center_hole_offset','d_actuator_bhc_offset','hole_grid_length','hole_grid_width'];
const displayLabel=(key:string)=>key.replaceAll('_',' ').replace(/\b(id|bhc|od|sq|d)\b/gi,value=>value.toUpperCase()).replace(/\b\w/g,value=>value.toUpperCase());
const referenceFields=(keys:string[])=>keys.map((field_key,index)=>({field_key,label:displayLabel(field_key),sort_order:(index+1)*10,is_visible:1,is_highlighted:0,unit:null as string|null,decimal_places:null as number|null,help_text:null as string|null}));
export const defaultReferenceDisplays={actuators:referenceFields(actuatorColumns),brackets:referenceFields(bracketColumns)};
