import initSqlJs, {type Database, type SqlJsStatic} from 'sql.js';
import wasmUrl from 'sql.js/dist/sql-wasm.wasm?url';
import bcrypt from 'bcryptjs';
import {defaultFields,defaultReferenceDisplays,defaultSections} from './default-settings';

type User={id:number;username:string;role:'admin'|'user';password_hash:string;is_active:number;created_at:string;last_login_at?:string|null};
type Settings={version:number;users:User[];displaySections:any[];displayFields:any[];referenceDisplays:Record<'actuators'|'brackets',any[]>;databaseSources:any[];auditLogs:any[];updatedAt:string|null};
type RepoConfig={owner:string;repository:string;branch:string;settingsPath:string;hardwarePath:string;manufacturingPath:string};
type Source='hardware_configurator'|'manufacturing_log';
const base=import.meta.env.BASE_URL;
let SQL:SqlJsStatic,settings:Settings,repo:RepoConfig,hardware:Database|null=null,manufacturing:Database|null=null,ready:Promise<void>|null=null;
const now=()=>new Date().toISOString().slice(0,19).replace('T',' ');
const tokenKey='vdb.githubToken',sessionKey='vdb.sessionUser',settingsKey='vdb.settingsCache';
const hardwareTables:Record<string,string[]>={
 valves:['valve_id','valve_brand','valve_size','valve_class','valve_model_number','valve_port','stem_type','description'],
 valve_keyed_stems:['valve_id','stem_diameter','stem_height','key_qty','key_width','key_cross','valve_bhc','valve_hole_dia','valve_hole_qty','valve_start_angle'],
 valve_flat_stems:['valve_id','stem_height','flat_width','flat_depth','valve_bhc','valve_hole_dia','valve_hole_qty','valve_start_angle','packing_flange','packing_flange_width','packing_flange_length','packing_flange_angle','dia_reduction','dia_reduction_value','stem_thread','stem_thread_dia','stem_thread_depth','u_bolt','u_bolt_valve_width','u_bolt_valve_length','valve_pattern_type','valve_grid_x_distance','valve_grid_y_distance'],
 actuator_sets:['actuator_id','actuator_name','theme_name','square_size','square_height','sq_rad','d_stem','actuator_hole_dia','actuator_bhc','actuator_hole_qty','actuator_start_angle','bracket_height'],
 bracket_patterns:['bracket_id','bracket_code','actuator_1_bhc','actuator_1_hole_dia','actuator_1_hole_qty','actuator_1_start_angle','actuator_2_bhc','actuator_2_hole_dia','actuator_2_hole_qty','actuator_2_start_angle','actuator_3_bhc','actuator_3_hole_dia','actuator_3_hole_qty','actuator_3_start_angle','valve_bhc','valve_hole_dia','valve_hole_qty','valve_start_angle','valve_2_bhc','valve_2_hole_dia','valve_2_hole_qty','valve_2_start_angle','valve_3_bhc','valve_3_hole_dia','valve_3_hole_qty','valve_3_start_angle','bracket_width','bracket_length','bracket_height','actuator_bracket_center_hole','valve_bracket_center_hole','packing_flange','packing_flange_width','packing_flange_length','packing_flange_angle','d_actuator_bracket_center_hole_offset','d_actuator_bhc_offset','hole_grid_length','hole_grid_width'],
 universal_adapters:['id','universal_adapter_name','square_size','square_height','sq_rad','one_p_adapter_length','actuator_name','adapter_od_fixed']
};
const manufacturingColumns=['id','timestamp','job_number','quantity','configuration_name','fusion_document_name','valve_id','valve_brand','valve_size','valve_class','valve_port','valve_model','actuator_name','Packing Flange','SCHA','U-Bolt','diameter reduction','stem thread','Body_Height','Hub_Height','Hub_ID','Hub_OD','actuator_bhc','actuator_bracket_center_hole','actuator_hole_dia','bracket_code','bracket_height','dia_reduction','flat_depth','flat_width','key_cross','key_width','packing_flange_angle','packing_flange_length','packing_flange_width','slot_depth','slot_width','square_height','square_size','stem_diameter','stem_height','valve_bhc','valve_bracket_center_hole','valve_hole_dia','valve_hole_qty','Adapter_OD','actuator_hole_qty','bracket_length','bracket_width','Bolt Pattern'];

async function initialize(){const previousSessionToken=sessionStorage.getItem(tokenKey);if(previousSessionToken&&!localStorage.getItem(tokenKey))localStorage.setItem(tokenKey,previousSessionToken);const previousLogin=sessionStorage.getItem(sessionKey);if(previousLogin&&!localStorage.getItem(sessionKey))localStorage.setItem(sessionKey,previousLogin);repo=await fetchJson<RepoConfig>('data/app-config.json');const remote=await fetchJson<Settings>('data/settings.json');const cached=parse<Settings>(localStorage.getItem(settingsKey));settings=cached?.updatedAt&&(!remote.updatedAt||cached.updatedAt>remote.updatedAt)?cached:remote;settings.displaySections=settings.displaySections?.length?settings.displaySections:structuredClone(defaultSections);settings.displayFields=settings.displayFields?.length?settings.displayFields:structuredClone(defaultFields);mergeMissingDisplayFields();const summarySection=settings.displaySections.find(x=>x.section_key==='manufacturing');if(summarySection?.label==='Manufacturing Summary')summarySection.label='Configurator & Drawing Summary';settings.referenceDisplays={actuators:settings.referenceDisplays?.actuators?.length?settings.referenceDisplays.actuators:structuredClone(defaultReferenceDisplays.actuators),brackets:settings.referenceDisplays?.brackets?.length?settings.referenceDisplays.brackets:structuredClone(defaultReferenceDisplays.brackets)};settings.users||=[];settings.databaseSources||=[];settings.auditLogs||=[];SQL=await initSqlJs({locateFile:()=>wasmUrl});await Promise.all([loadDatabase('hardware_configurator'),loadDatabase('manufacturing_log')]);}
function mergeMissingDisplayFields(){const keys=new Set(settings.displayFields.map(x=>x.field_key)),ids=new Set(settings.displayFields.map(x=>x.id));let nextId=Math.max(0,...ids)+1;for(const field of defaultFields)if(!keys.has(field.field_key)){const id=ids.has(field.id)?nextId++:field.id;ids.add(id);settings.displayFields.push({...structuredClone(field),id})}}
const ensure=()=>ready||=(initialize());
async function fetchJson<T>(path:string){const r=await fetch(`${base}${path}?v=${Date.now()}`);if(!r.ok)throw new Error(`Unable to load ${path}`);return r.json() as Promise<T>}
function parse<T>(value:string|null):T|null{try{return value?JSON.parse(value):null}catch{return null}}
function currentUser(){return parse<Omit<User,'password_hash'>>(localStorage.getItem(sessionKey))}
function requireUser(admin=false){const u=currentUser();if(!u)throw error('Authentication required',401);if(admin&&u.role!=='admin')throw error('Administrator access required',403);return u}
function error(message:string,status=400){return Object.assign(new Error(message),{status})}
function rows(db:Database,sql:string,params:any[]=[]):any[]{const statement=db.prepare(sql);try{statement.bind(params);const out=[];while(statement.step())out.push(statement.getAsObject());return out}finally{statement.free()}}
function value(db:Database,sql:string,params:any[]=[]){return rows(db,sql,params)[0]}
async function loadDatabase(type:Source){const source=settings.databaseSources.find(x=>x.source_type===type);const cached=source?.sha?await idbGet(`${type}:${source.sha}`):null;let bytes=cached;if(!bytes){const file=type==='hardware_configurator'?'data/active/hardware_configurator.db':'data/active/manufacturing_log.db';const response=await fetch(`${base}${file}?v=${source?.sha||Date.now()}`);if(response.ok)bytes=new Uint8Array(await response.arrayBuffer())}if(bytes){const db=new SQL.Database(bytes);if(type==='hardware_configurator')hardware=db;else manufacturing=db}}
function dbFor(type:Source){const db=type==='hardware_configurator'?hardware:manufacturing;if(!db)throw error(`${type.replaceAll('_',' ')} database is not active`,503);return db}
function validate(type:Source,bytes:Uint8Array){let db:Database;try{db=new SQL.Database(bytes)}catch{throw error('The selected file is not a valid SQLite database')};try{const integrity=String(value(db,'PRAGMA integrity_check')?.integrity_check||'failed');if(integrity!=='ok')throw error(`SQLite integrity check failed: ${integrity}`);const required=type==='hardware_configurator'?hardwareTables:{manufacturing_log:manufacturingColumns};const tables=new Set(rows(db,"SELECT name FROM sqlite_master WHERE type='table'").map(x=>x.name));const issues:any[]=[];const rowCounts:Record<string,number>={};for(const[table,columns]of Object.entries(required)){if(!tables.has(table)){issues.push({level:'error',message:`Missing required table: ${table}`});continue}const actual=new Set(rows(db,`PRAGMA table_info("${table}")`).map(x=>x.name));for(const column of columns)if(!actual.has(column))issues.push({level:'error',message:`${table} is missing required column: ${column}`});rowCounts[table]=Number(value(db,`SELECT COUNT(*) n FROM "${table}"`).n)}if(issues.length)throw error(issues.map(x=>x.message).join('; '));return{valid:true,sourceType:type,integrityCheck:integrity,rowCounts,issues,details:{browserValidation:true}}}finally{db.close()}}
function sessionSource(type:Source,bytes:Uint8Array){if(type==='hardware_configurator'){hardware?.close();hardware=new SQL.Database(bytes)}else{manufacturing?.close();manufacturing=new SQL.Database(bytes)}}
function githubXhr(url:string,options:RequestInit={}):Promise<Response>{return new Promise((resolve,reject)=>{const request=new XMLHttpRequest();request.open(options.method||'GET',url,true);request.timeout=120000;new Headers(options.headers).forEach((value,key)=>request.setRequestHeader(key,value));request.onload=()=>resolve(new Response(request.responseText,{status:request.status,statusText:request.statusText}));request.onerror=()=>reject(new Error('GitHub API network request was blocked'));request.ontimeout=()=>reject(new Error('GitHub API request timed out'));request.send(typeof options.body==='string'?options.body:null)})}
async function githubFetch(url:string,options:RequestInit={}){try{return await fetch(url,{...options,credentials:'omit'})}catch(fetchFailure){try{return await githubXhr(url,options)}catch(xhrFailure){const fetchMessage=fetchFailure instanceof Error?fetchFailure.message:'fetch failed',xhrMessage=xhrFailure instanceof Error?xhrFailure.message:'fallback failed';throw error(`Unable to reach the GitHub API (${fetchMessage}; ${xhrMessage}). Allow api.github.com in browser privacy/ad-blocking settings and try again.`)}}}
async function connectGitHub(rawToken:string){const token=rawToken.trim();const response=await githubFetch('https://api.github.com/user',{headers:githubHeaders(token)});if(!response.ok)throw error('GitHub token was rejected. Use a fine-grained token with Contents read/write access.');const user=await response.json();localStorage.setItem(tokenKey,token);return{login:user.login}}
function githubHeaders(token:string){return{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'}}
async function githubWrite(path:string,bytes:Uint8Array,message:string){
 let token=localStorage.getItem(tokenKey);
 if(!token){token=window.prompt(`Enter a fine-grained GitHub token with Contents read/write access to ${repo.owner}/${repo.repository}. It will be saved only in this browser.`)?.trim()||'';if(!token)throw error('A GitHub token is required to change repository data');await connectGitHub(token)}
 const endpoint=`https://api.github.com/repos/${repo.owner}/${repo.repository}/contents/${path}`;
 const currentSha=async()=>{const current=await githubFetch(`${endpoint}?ref=${encodeURIComponent(repo.branch)}&cacheBust=${Date.now()}-${crypto.randomUUID()}`,{headers:githubHeaders(token)});if(current.ok)return String((await current.json()).sha);if(current.status===401){localStorage.removeItem(tokenKey);throw error('The saved GitHub token was rejected and has been removed. Try the upload again with a new token.')}if(current.status===404)return undefined;throw error(`GitHub could not read ${path} (${current.status})`)};
 for(let attempt=0;attempt<2;attempt++){
  const sha=await currentSha();
  const response=await githubFetch(endpoint,{method:'PUT',headers:{...githubHeaders(token),'Content-Type':'application/json'},body:JSON.stringify({message,content:toBase64(bytes),branch:repo.branch,...(sha?{sha}:{})})});
  if(response.ok)return response.json();
  const detail=await response.json().catch(()=>({})) as {message?:string};
  if(response.status===401){localStorage.removeItem(tokenKey);throw error('The saved GitHub token was rejected and has been removed. Try the upload again with a new token.')}
  const staleSha=(response.status===409||response.status===422)&&/does not match|sha/i.test(detail.message||'');
  if(staleSha&&attempt===0)continue;
  throw error(detail.message||`GitHub upload failed (${response.status})`);
 }
 throw error(`GitHub could not update ${path} after refreshing its current version`);
}
function toBase64(bytes:Uint8Array){let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)}
async function persistSettings(message:string){settings.updatedAt=new Date().toISOString();const result=await githubWrite(repo.settingsPath,new TextEncoder().encode(JSON.stringify(settings,null,2)+'\n'),message);localStorage.setItem(settingsKey,JSON.stringify(settings));return result.content?.sha}
function audit(action:string,entity?:string,details?:any){const u=currentUser();settings.auditLogs.unshift({id:Date.now(),username:u?.username||'System',action,entity_type:entity||null,details:details?JSON.stringify(details):null,created_at:now()});settings.auditLogs=settings.auditLogs.slice(0,200)}
function queryParams(url:string){return new URL(url,'https://local.invalid').searchParams}

export async function localApi<T>(url:string,options:RequestInit={}):Promise<T>{await ensure();const method=options.method||'GET',path=url.split('?')[0],body=options.body instanceof FormData?options.body:options.body?JSON.parse(String(options.body)):{};
 if(path==='/auth/session')return{user:currentUser(),csrfToken:'static-pages'} as T;
 if(path==='/auth/setup-status')return{required:settings.users.length===0} as T;
 if(path==='/auth/login'&&method==='POST'){const u=settings.users.find(x=>x.username.toLowerCase()===String(body.username).toLowerCase());if(!u||!u.is_active||!await bcrypt.compare(body.password,u.password_hash))throw error('Invalid username or password',401);u.last_login_at=now();const safe={id:u.id,username:u.username,role:u.role};localStorage.setItem(sessionKey,JSON.stringify(safe));return{user:safe,csrfToken:'static-pages'} as T}
 if(path==='/auth/setup'&&method==='POST'){if(settings.users.length)throw error('Initial setup has already been completed',409);if(!body.githubToken)throw error('A GitHub access token is required for initial setup');await connectGitHub(body.githubToken);if(String(body.password).length<4)throw error('Password must be at least 4 characters');const u:User={id:1,username:String(body.username).trim(),role:'admin',password_hash:await bcrypt.hash(body.password,10),is_active:1,created_at:now()};settings.users=[u];audit('system.initial_setup','user');await persistSettings('Initialize Valve Database Viewer administrator');localStorage.setItem(sessionKey,JSON.stringify({id:1,username:u.username,role:'admin'}));return{user:{id:1,username:u.username,role:'admin'},csrfToken:'static-pages'} as T}
 if(path==='/auth/logout'){localStorage.removeItem(sessionKey);sessionStorage.removeItem(sessionKey);return null as T}
 if(path==='/admin/github/status'){requireUser(true);const token=localStorage.getItem(tokenKey);return{connected:!!token,repository:`${repo.owner}/${repo.repository}`} as T}
 if(path==='/admin/github/connect'&&method==='POST'){requireUser(true);return await connectGitHub(body.token) as T}
 if(path==='/admin/github/disconnect'&&method==='POST'){localStorage.removeItem(tokenKey);return{ok:true} as T}
 if(path==='/display-config'){requireUser();return{sections:settings.displaySections.filter(x=>x.is_visible).sort(sortOrder),fields:settings.displayFields.filter(x=>x.is_visible).sort(sortOrder)} as T}
 if(path==='/valves/brands'){requireUser();return rows(dbFor('hardware_configurator'),"SELECT DISTINCT valve_brand value FROM valves WHERE valve_brand IS NOT NULL AND TRIM(valve_brand)<>'' ORDER BY valve_brand COLLATE NOCASE").map(x=>x.value) as T}
 const params=queryParams(url);
 if(path==='/valves/sizes'){requireUser();return rows(dbFor('hardware_configurator'),"SELECT DISTINCT valve_size value FROM valves WHERE valve_brand=? AND TRIM(COALESCE(valve_size,''))<>'' ORDER BY CASE WHEN TRIM(valve_size) GLOB '[0-9]*' THEN CAST(valve_size AS REAL) END,valve_size COLLATE NOCASE",[params.get('brand')]).map(x=>x.value) as T}
 if(path==='/valves/classes'){requireUser();return rows(dbFor('hardware_configurator'),"SELECT DISTINCT valve_class value FROM valves WHERE valve_brand=? AND valve_size=? AND TRIM(COALESCE(valve_class,''))<>'' ORDER BY CASE WHEN TRIM(valve_class) GLOB '[0-9]*' THEN CAST(valve_class AS INTEGER) END,valve_class COLLATE NOCASE",[params.get('brand'),params.get('size')]).map(x=>x.value) as T}
 if(path==='/valves/models'){requireUser();return rows(dbFor('hardware_configurator'),"SELECT valve_id valveId,valve_model_number model FROM valves WHERE valve_brand=? AND valve_size=? AND valve_class=? AND TRIM(COALESCE(valve_model_number,''))<>'' ORDER BY valve_model_number COLLATE NOCASE",[params.get('brand'),params.get('size'),params.get('class')]) as T}
 if(path==='/configurator/actuators'){requireUser();return rows(dbFor('hardware_configurator'),'SELECT actuator_id actuatorId,actuator_name name,theme_name theme,square_size squareSize,actuator_bhc bhc FROM actuator_sets ORDER BY CASE WHEN actuator_name GLOB \'[0-9]*\' THEN CAST(actuator_name AS REAL) END,actuator_name COLLATE NOCASE') as T}
 if(path==='/configurator/results'){requireUser();return configuratorResults(Number(params.get('valveId')),Number(params.get('actuatorId'))) as T}
 const valveMatch=path.match(/^\/valves\/(\d+)$/);if(valveMatch){requireUser();return valveDetail(Number(valveMatch[1])) as T}
 const summaryMatch=path.match(/^\/valves\/(\d+)\/manufacturing-summary$/);if(summaryMatch){requireUser();const h=history(Number(summaryMatch[1])),last=h[0];return{lastManufacturedTimestamp:last?.timestamp??null,lastJobNumber:last?.job_number??null,lastQuantity:last?.quantity??null,lastConfigurationName:last?.configuration_name??null,lastFusionDocument:last?.fusion_document_name??null,lastActuator:last?.actuator_name??null,totalManufacturingRuns:h.length} as T}
 const historyMatch=path.match(/^\/valves\/(\d+)\/manufacturing-history$/);if(historyMatch){requireUser();return history(Number(historyMatch[1])) as T}
 if(path==='/reference-display'){requireUser();const type=queryParams(url).get('type') as 'actuators'|'brackets';if(!['actuators','brackets'].includes(type))throw error('Unknown reference display');return settings.referenceDisplays[type].filter(x=>x.is_visible).sort(sortOrder) as T}
 if(path==='/admin/actuator-sets'){requireUser();return rows(dbFor('hardware_configurator'),'SELECT * FROM actuator_sets ORDER BY actuator_id') as T}
 if(path==='/admin/bracket-patterns'){requireUser();return rows(dbFor('hardware_configurator'),'SELECT * FROM bracket_patterns ORDER BY bracket_id') as T}
 requireUser(true);
 if(path==='/admin/database-sources')return settings.databaseSources as T;
 if(path==='/admin/database-sources/cross-validation')return crossValidation() as T;
 const uploadMatch=path.match(/^\/admin\/database-sources\/(hardware-configurator|manufacturing-log)\/upload$/);if(uploadMatch){const file=(body as FormData).get('database') as File;if(!file)throw error('Choose a database file');const type:Source=uploadMatch[1]==='hardware-configurator'?'hardware_configurator':'manufacturing_log';return await saveDatabase(type,new Uint8Array(await file.arrayBuffer()),file.name) as T}
 if(path==='/admin/display-sections')return settings.displaySections.sort(sortOrder) as T;
 if(path==='/admin/display-fields')return settings.displayFields.sort(sortOrder) as T;
 if(path==='/admin/reference-display')return settings.referenceDisplays as T;
 if(path==='/admin/display-config'&&method==='PUT'){
  const incomingSections=Array.isArray(body.sections)?body.sections:[],incomingFields=Array.isArray(body.fields)?body.fields:[],incomingReferences=body.referenceDisplays;
  if(incomingSections.length!==settings.displaySections.length||incomingFields.length!==settings.displayFields.length)throw error('Display configuration is incomplete; reload the page and try again');
  const sectionIds=new Set(settings.displaySections.map(x=>x.id)),fieldIds=new Set(settings.displayFields.map(x=>x.id)),sectionKeys=new Set(incomingSections.map((x:any)=>x.section_key));
  if(incomingSections.some((x:any)=>!sectionIds.has(x.id))||incomingFields.some((x:any)=>!fieldIds.has(x.id)||!sectionKeys.has(x.section_key)))throw error('Display configuration contains unknown sections or fields');
  settings.displaySections=incomingSections.map((x:any,index:number)=>({...settings.displaySections.find(current=>current.id===x.id),label:String(x.label).slice(0,100),sort_order:(index+1)*10,is_visible:x.is_visible?1:0}));
  settings.displayFields=incomingFields.map((x:any)=>normalizeDisplayField(settings.displayFields.find(current=>current.id===x.id),x));
  for(const type of ['actuators','brackets'] as const){
   const incoming=Array.isArray(incomingReferences?.[type])?incomingReferences[type]:[];
   const existing=settings.referenceDisplays[type],known=new Set(existing.map(x=>x.field_key));
   if(incoming.length!==existing.length||incoming.some((x:any)=>!known.has(x.field_key)))throw error(`${type} display configuration is incomplete; reload the page and try again`);
   settings.referenceDisplays[type]=incoming.map((x:any,index:number)=>normalizeDisplayField(existing.find(current=>current.field_key===x.field_key),{...x,sort_order:(index+1)*10}));
  }
  audit('display.configuration.update','display_configuration',{sections:settings.displaySections.length,fields:settings.displayFields.length});await persistSettings('Update complete display configuration');return{ok:true} as T
 }
 const sectionMatch=path.match(/^\/admin\/display-sections\/(\d+)$/);if(sectionMatch&&method==='PUT'){Object.assign(settings.displaySections.find(x=>x.id===Number(sectionMatch[1])),body);audit('display.section.update','display_section',body);await persistSettings('Update display section');return{ok:true} as T}
 const fieldMatch=path.match(/^\/admin\/display-fields\/(\d+)$/);if(fieldMatch&&method==='PUT'){Object.assign(settings.displayFields.find(x=>x.id===Number(fieldMatch[1])),body);audit('display.field.update','display_field',body);await persistSettings('Update display field');return{ok:true} as T}
 if(path==='/admin/users'&&method==='GET')return settings.users.map(({password_hash,...u})=>u) as T;
 if(path==='/admin/users'&&method==='POST'){if(String(body.password).length<4)throw error('Password must be at least 4 characters');if(settings.users.some(x=>x.username.toLowerCase()===String(body.username).toLowerCase()))throw error('That username already exists');const user:User={id:Math.max(0,...settings.users.map(x=>x.id))+1,username:body.username,role:body.role,password_hash:await bcrypt.hash(body.password,10),is_active:1,created_at:now()};settings.users.push(user);audit('user.create','user',{username:user.username,role:user.role});await persistSettings('Add Valve Database Viewer user');return{id:user.id} as T}
 const userMatch=path.match(/^\/admin\/users\/(\d+)$/);if(userMatch&&method==='PUT'){const u=settings.users.find(x=>x.id===Number(userMatch[1]));if(!u)throw error('User not found',404);u.role=body.role;u.is_active=body.is_active?1:0;audit('user.update','user',{id:u.id});await persistSettings('Update Valve Database Viewer user');return{ok:true} as T}
 const resetMatch=path.match(/^\/admin\/users\/(\d+)\/reset-password$/);if(resetMatch){const u=settings.users.find(x=>x.id===Number(resetMatch[1]));if(!u)throw error('User not found',404);if(String(body.password).length<4)throw error('Password must be at least 4 characters');u.password_hash=await bcrypt.hash(body.password,10);audit('user.password_reset','user',{id:u.id});await persistSettings('Reset Valve Database Viewer password');return{ok:true} as T}
 if(path==='/admin/audit-logs')return settings.auditLogs as T;
 if(path==='/admin/actuator-sets')return rows(dbFor('hardware_configurator'),'SELECT * FROM actuator_sets ORDER BY actuator_id') as T;
 if(path==='/admin/bracket-patterns')return rows(dbFor('hardware_configurator'),'SELECT * FROM bracket_patterns ORDER BY bracket_id') as T;
 if(path==='/admin/universal-adapters')return rows(dbFor('hardware_configurator'),'SELECT * FROM universal_adapters ORDER BY id') as T;
 if(path==='/admin/dashboard')return dashboard() as T;
 throw error(`Static API route is not implemented: ${method} ${path}`,404)
}
function sortOrder(a:any,b:any){return a.sort_order-b.sort_order||a.id-b.id}
function normalizeDisplayField(current:any,incoming:any){return{...current,label:String(incoming.label).slice(0,100),...(incoming.section_key?{section_key:incoming.section_key}:{}),sort_order:Number(incoming.sort_order),is_visible:incoming.is_visible?1:0,is_highlighted:incoming.is_highlighted?1:0,unit:incoming.unit?String(incoming.unit).slice(0,30):null,decimal_places:incoming.decimal_places===null?null:Math.max(0,Math.min(10,Number(incoming.decimal_places))),help_text:incoming.help_text?String(incoming.help_text).slice(0,500):null}}
function valveDetail(id:number){return value(dbFor('hardware_configurator'),`SELECT v.valve_id,v.valve_brand,v.valve_size,v.valve_class,v.valve_model_number,v.valve_port,v.stem_type,v.description,k.stem_diameter keyed_stem_diameter,k.stem_height keyed_stem_height,k.key_qty,k.key_width,k.key_cross,k.valve_bhc keyed_valve_bhc,k.valve_hole_dia keyed_valve_hole_dia,k.valve_hole_qty keyed_valve_hole_qty,k.valve_start_angle keyed_valve_start_angle,f.stem_height flat_stem_height,f.flat_width,f.flat_depth,f.valve_bhc flat_valve_bhc,f.valve_hole_dia flat_valve_hole_dia,f.valve_hole_qty flat_valve_hole_qty,f.valve_start_angle flat_valve_start_angle,f.packing_flange,f.packing_flange_width,f.packing_flange_length,f.packing_flange_angle,f.dia_reduction,f.dia_reduction_value,f.stem_thread,f.stem_thread_dia,f.stem_thread_depth,f.u_bolt,f.u_bolt_valve_width,f.u_bolt_valve_length,f.valve_pattern_type,f.valve_grid_x_distance,f.valve_grid_y_distance,CASE WHEN v.stem_type='KEYED' AND k.valve_id IS NULL THEN 1 WHEN v.stem_type='FLATS' AND f.valve_id IS NULL THEN 1 ELSE 0 END stem_detail_missing FROM valves v LEFT JOIN valve_keyed_stems k ON k.valve_id=v.valve_id AND v.stem_type='KEYED' LEFT JOIN valve_flat_stems f ON f.valve_id=v.valve_id AND v.stem_type='FLATS' WHERE v.valve_id=?`,[id])||null}
function history(id:number){return rows(dbFor('manufacturing_log'),"SELECT * FROM manufacturing_log WHERE valve_id GLOB '[0-9]*' AND valve_id NOT GLOB '*[^0-9]*' AND CAST(valve_id AS INTEGER)=? ORDER BY datetime(timestamp) DESC,id DESC",[id])}
const near=(a:any,b:any,tolerance=.03)=>a!==null&&a!==undefined&&b!==null&&b!==undefined&&Math.abs(Number(a)-Number(b))<=tolerance;
const sameAngle=(a:any,b:any)=>a!==null&&a!==undefined&&b!==null&&b!==undefined&&(near(a,b,.51)||near((Number(a)+90)%90,(Number(b)+90)%90,.51));
function roundValue(value:any){return value===null||value===undefined?null:Number(Number(value).toFixed(4))}
function mountPatternMatches(item:any,pattern:any,prefix:string){return near(item.bhc,pattern[`${prefix}_bhc`])&&near(item.holeDia,pattern[`${prefix}_hole_dia`])&&Number(item.holeQty)===Number(pattern[`${prefix}_hole_qty`])&&sameAngle(item.angle,pattern[`${prefix}_start_angle`])}
function packingMatches(valve:any,bracket:any){const required=/^yes$/i.test(String(valve.packing_flange||'')),provided=/^yes$/i.test(String(bracket.packing_flange||''));if(!required)return!provided;if(!provided)return false;const direct=near(valve.packing_flange_width,bracket.packing_flange_width,.08)&&near(valve.packing_flange_length,bracket.packing_flange_length,.08),rotated=near(valve.packing_flange_width,bracket.packing_flange_length,.08)&&near(valve.packing_flange_length,bracket.packing_flange_width,.08);return(direct||rotated)&&sameAngle(valve.packing_flange_angle,bracket.packing_flange_angle)}
function configuratorResults(valveId:number,actuatorId:number){
 const hardwareDb=dbFor('hardware_configurator'),valve=valveDetail(valveId),actuator=value(hardwareDb,'SELECT * FROM actuator_sets WHERE actuator_id=?',[actuatorId]);if(!valve||!actuator)throw error('Select a valid valve and actuator');
 const actuatorMount={bhc:actuator.actuator_bhc,holeDia:actuator.actuator_hole_dia,holeQty:actuator.actuator_hole_qty,angle:actuator.actuator_start_angle};
 const valveMount={bhc:valve.stem_type==='KEYED'?valve.keyed_valve_bhc:valve.flat_valve_bhc,holeDia:valve.stem_type==='KEYED'?valve.keyed_valve_hole_dia:valve.flat_valve_hole_dia,holeQty:valve.stem_type==='KEYED'?valve.keyed_valve_hole_qty:valve.flat_valve_hole_qty,angle:valve.stem_type==='KEYED'?valve.keyed_valve_start_angle:valve.flat_valve_start_angle};
 let prior:any[]=[];try{prior=history(valveId).filter(row=>String(row.actuator_name||'').trim().toLowerCase()===String(actuator.actuator_name).trim().toLowerCase())}catch{}
 const historicalCodes=new Set(prior.map(row=>String(row.bracket_code||'').trim().toLowerCase()).filter(code=>code&&code!=='0'));
 const brackets=rows(hardwareDb,'SELECT * FROM bracket_patterns ORDER BY bracket_code COLLATE NOCASE').map(bracket=>{
  const actuatorPattern=[1,2,3].find(index=>mountPatternMatches(actuatorMount,bracket,`actuator_${index}`));
  const namedActuator=String(bracket.bracket_code||'').trim().toLowerCase()===String(actuator.actuator_name).trim().toLowerCase();
  const bhcValvePattern=[1,2,3].find(index=>mountPatternMatches(valveMount,bracket,index===1?'valve':`valve_${index}`));
  const gridValvePattern=valve.valve_pattern_type==='GRID'&&((near(valve.valve_grid_x_distance,bracket.hole_grid_length,.08)&&near(valve.valve_grid_y_distance,bracket.hole_grid_width,.08))||(near(valve.valve_grid_x_distance,bracket.hole_grid_width,.08)&&near(valve.valve_grid_y_distance,bracket.hole_grid_length,.08)));
  const geometryMatch=!!(actuatorPattern||namedActuator)&&!!(bhcValvePattern||gridValvePattern)&&packingMatches(valve,bracket),previouslyUsed=historicalCodes.has(String(bracket.bracket_code||'').trim().toLowerCase());
  if(!geometryMatch&&!previouslyUsed)return null;return{...bracket,geometryMatch,previouslyUsed,actuatorPattern:actuatorPattern?`Actuator pattern ${actuatorPattern}`:namedActuator?'Actuator-specific bracket':null,valvePattern:bhcValvePattern?`Valve pattern ${bhcValvePattern}`:gridValvePattern?'Valve grid pattern':null};
 }).filter(Boolean);
 const actuatorName=String(actuator.actuator_name).trim().toLowerCase(),adapters=rows(hardwareDb,'SELECT * FROM universal_adapters ORDER BY universal_adapter_name COLLATE NOCASE').filter(adapter=>String(adapter.actuator_name||'').split(/[^a-z0-9.-]+/i).some(name=>name.toLowerCase()===actuatorName)&&near(adapter.square_size,actuator.square_size,.01)).map(adapter=>({...adapter,reason:`Recorded for actuator ${actuator.actuator_name} with ${roundValue(adapter.square_size)} square`}));
 return{valve:{id:valve.valve_id,brand:valve.valve_brand,size:valve.valve_size,class:valve.valve_class,model:valve.valve_model_number,stemType:valve.stem_type,mount:{bhc:roundValue(valveMount.bhc),holeDia:roundValue(valveMount.holeDia),holeQty:valveMount.holeQty,angle:roundValue(valveMount.angle),patternType:valve.valve_pattern_type||'BHC'}},actuator:{id:actuator.actuator_id,name:actuator.actuator_name,theme:actuator.theme_name,squareSize:roundValue(actuator.square_size),mount:{bhc:roundValue(actuatorMount.bhc),holeDia:roundValue(actuatorMount.holeDia),holeQty:actuatorMount.holeQty,angle:roundValue(actuatorMount.angle)}},brackets,adapters,priorUses:prior.length,notes:['Dimensional matches compare mounting dimensions with a small tolerance for rounded source values.','Previously used means the manufacturing log records that exact valve and actuator with the bracket code.','Universal adapters are actuator-compatible options; verify final valve-stem machining before release.']};
}
async function saveDatabase(type:Source,bytes:Uint8Array,name:string){if(bytes.byteLength>50*1024*1024)throw error('Browser-to-GitHub uploads are limited to 50 MB');let stage='SQLite validation';try{const report=validate(type,bytes);const path=type==='hardware_configurator'?repo.hardwarePath:repo.manufacturingPath;stage='database file commit';const result=await githubWrite(path,bytes,`Update ${type} database from Valve Database Viewer`);const sha=result.content.sha;stage='browser database cache';await idbPut(`${type}:${sha}`,bytes);sessionSource(type,bytes);const meta={source_type:type,original_file_name:name,file_size_bytes:bytes.byteLength,uploaded_at:now(),validation_status:'valid',validationReport:report,sha};settings.databaseSources=settings.databaseSources.filter(x=>x.source_type!==type);settings.databaseSources.push(meta);audit('database.upload','database_source',{type,name});stage='settings metadata commit';await persistSettings(`Update ${type} metadata`);return report}catch(cause){const message=cause instanceof Error?cause.message:String(cause);throw error(`Upload failed during ${stage}: ${message}`)}}
function crossValidation(){if(!hardware||!manufacturing)return{status:'pending',message:'Both databases must be active'};const valves=rows(hardware,'SELECT valve_id,valve_brand,valve_size,valve_class,valve_model_number FROM valves'),logs=rows(manufacturing,'SELECT valve_id,valve_brand,valve_size,valve_class,valve_model FROM manufacturing_log'),map=new Map(valves.map(v=>[Number(v.valve_id),v]));let matched=0,mismatches=0;const used=new Set<number>();for(const log of logs){const id=/^\d+$/.test(String(log.valve_id))?Number(log.valve_id):NaN,v=map.get(id);if(v){matched++;used.add(id);if(log.valve_brand!==v.valve_brand||log.valve_size!==v.valve_size||log.valve_class!==v.valve_class||log.valve_model!==v.valve_model_number)mismatches++}}return{status:'complete',configuratorValves:valves.length,manufacturingRows:logs.length,matchedManufacturingRows:matched,unmatchedManufacturingRows:logs.length-matched,valvesWithHistory:used.size,valvesNeverManufactured:valves.length-used.size,historicalIdentityMismatches:mismatches}}
function dashboard(){const cv:any=crossValidation(),counts:any={activeUsers:settings.users.filter(x=>x.is_active).length,recentAudit:settings.auditLogs.slice(0,8),latestUpload:[...settings.databaseSources].sort((a,b)=>String(b.uploaded_at).localeCompare(String(a.uploaded_at)))[0]||null};if(hardware)Object.assign(counts,{valveCount:Number(value(hardware,'SELECT COUNT(*) n FROM valves').n),keyedStemCount:Number(value(hardware,'SELECT COUNT(*) n FROM valve_keyed_stems').n),flatStemCount:Number(value(hardware,'SELECT COUNT(*) n FROM valve_flat_stems').n),actuatorSetCount:Number(value(hardware,'SELECT COUNT(*) n FROM actuator_sets').n),bracketPatternCount:Number(value(hardware,'SELECT COUNT(*) n FROM bracket_patterns').n),universalAdapterCount:Number(value(hardware,'SELECT COUNT(*) n FROM universal_adapters').n)});return{...counts,...cv}}
function idbGet(key:string):Promise<Uint8Array|null>{return new Promise(resolve=>{const request=indexedDB.open('valve-database-viewer',1);request.onupgradeneeded=()=>request.result.createObjectStore('databases');request.onerror=()=>resolve(null);request.onsuccess=()=>{const tx=request.result.transaction('databases'),get=tx.objectStore('databases').get(key);get.onsuccess=()=>resolve(get.result||null);get.onerror=()=>resolve(null)}})}
function idbPut(key:string,value:Uint8Array):Promise<void>{return new Promise((resolve,reject)=>{const request=indexedDB.open('valve-database-viewer',1);request.onupgradeneeded=()=>request.result.createObjectStore('databases');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const tx=request.result.transaction('databases','readwrite');tx.objectStore('databases').put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)}})}
