import { beforeAll, describe, expect, it } from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import Database from 'better-sqlite3';import request from 'supertest';
import { hardwareSchema,manufacturingSchema } from '../scripts/demo-schema.js';

const root=fs.mkdtempSync(path.join(os.tmpdir(),'valve-viewer-test-'));process.env.DATA_DIR=root;process.env.SESSION_SECRET='test-secret-at-least-thirty-two-characters';process.env.INITIAL_ADMIN_USERNAME='admin';process.env.INITIAL_ADMIN_PASSWORD='a-secure-test-password';process.env.NODE_ENV='test';
const {LocalDatabaseSourceService}=await import('../services/database-source.js');const {SQLiteValveRepository}=await import('../repositories/valve.js');const {SQLiteManufacturingRepository}=await import('../repositories/manufacturing.js');const {ensureInitialAdmin,appDb}=await import('../db/app-db.js');const {createApp}=await import('../app.js');
const service=new LocalDatabaseSourceService();let hardwareFile='',manufacturingFile='';
function dbFile(name:string,schema:string){const f=path.join(root,name);const d=new Database(f);d.exec(schema);return{f,d}}
beforeAll(async()=>{await ensureInitialAdmin();let x=dbFile('valid-hardware.db',hardwareSchema);hardwareFile=x.f;x.d.exec(`INSERT INTO valves VALUES(1,'Acme','10','300','NEW-MODEL','Full','KEYED','Test'),(2,'Acme','2','150','FLAT-2','Full','FLATS','Test'),(3,'Acme','2.5','600','KEY-3','Reduced','KEYED','Test');INSERT INTO valve_keyed_stems(valve_id,stem_diameter) VALUES(1,1.25),(3,.75);INSERT INTO valve_flat_stems(valve_id,stem_height,flat_width,valve_pattern_type) VALUES(2,2.5,.6,'BHC');`);x.d.close();let y=dbFile('valid-manufacturing.db',manufacturingSchema);manufacturingFile=y.f;y.d.prepare(`INSERT INTO manufacturing_log(timestamp,job_number,quantity,configuration_name,valve_id,valve_brand,valve_size,valve_class,valve_model,"Body_Height") VALUES(?,?,?,?,?,?,?,?,?,?)`).run('2026-05-19 13:24:53','J-1','not numeric','C','1','Historical Brand','99','999','OLD-MODEL','1.41 in');y.d.close();service.activateUpload('hardware_configurator',hardwareFile,'../../escaped.db',1);service.activateUpload('manufacturing_log',manufacturingFile,'manufacturing.sqlite',1);});
describe('database validation and repositories',()=>{
 it('accepts both exact schemas',()=>{expect(service.validateUpload('hardware_configurator',hardwareFile).valid).toBe(true);expect(service.validateUpload('manufacturing_log',manufacturingFile).valid).toBe(true)});
 it('rejects corrupt SQLite input',()=>{const f=path.join(root,'corrupt.db');fs.writeFileSync(f,'not sqlite');expect(service.validateUpload('hardware_configurator',f).valid).toBe(false)});
 it('rejects a missing table',()=>{const{f,d}=dbFile('missing-table.db','CREATE TABLE valves(valve_id INTEGER)');d.close();const r=service.validateUpload('hardware_configurator',f);expect(r.valid).toBe(false);expect(r.issues.some(x=>x.code==='missing_table')).toBe(true)});
 it('rejects a missing required column',()=>{const{f,d}=dbFile('missing-column.db',hardwareSchema.replace(',description TEXT',''));d.close();const r=service.validateUpload('hardware_configurator',f);expect(r.valid).toBe(false);expect(r.issues.some(x=>x.message.includes('description'))).toBe(true)});
 it('keeps active database after failed replacement',()=>{const before=appDb.prepare("SELECT active_file_path FROM database_sources WHERE source_type='hardware_configurator'").get() as any;const bad=path.join(root,'bad-replacement.db');fs.writeFileSync(bad,'bad');expect(()=>service.activateUpload('hardware_configurator',bad,'bad.db',1)).toThrow();const after=appDb.prepare("SELECT active_file_path FROM database_sources WHERE source_type='hardware_configurator'").get() as any;expect(after.active_file_path).toBe(before.active_file_path);expect(fs.existsSync(after.active_file_path)).toBe(true)});
 it('uses correct keyed and flat joins',async()=>{const repo=new SQLiteValveRepository();expect((await repo.getValveById(1))?.keyed_stem_diameter).toBe(1.25);expect((await repo.getValveById(1))?.flat_stem_height).toBeNull();expect((await repo.getValveById(2))?.flat_stem_height).toBe(2.5)});
 it('cascades selectors and sorts sizes numerically',async()=>{const repo=new SQLiteValveRepository();expect(await repo.getBrands()).toEqual(['Acme']);expect(await repo.getSizes('Acme')).toEqual(['2','2.5','10']);expect(await repo.getClasses('Acme','2')).toEqual(['150']);expect(await repo.getModels('Acme','2','150')).toEqual([{valveId:2,model:'FLAT-2'}])});
 it('looks up history by text valve ID despite historical mismatch',async()=>{const repo=new SQLiteManufacturingRepository();const rows=await repo.getHistoryByValveId(1);expect(rows).toHaveLength(1);expect(rows[0].valve_brand).toBe('Historical Brand');expect(rows[0].Body_Height).toBe('1.41 in');expect(rows[0].quantity).toBe('not numeric')});
 it('sanitizes uploaded original filenames',()=>{const row=appDb.prepare("SELECT original_file_name FROM database_sources WHERE source_type='hardware_configurator'").get() as any;expect(row.original_file_name).toBe('escaped.db')});
});
describe('authorization and response safety',()=>{
 const app=createApp();
 it('blocks unauthenticated and non-admin access',async()=>{await request(app).get('/api/valves/brands').expect(401);const hash=await import('bcryptjs').then(m=>m.default.hash('ordinary-user-password',4));appDb.prepare("INSERT INTO users(username,password_hash,role) VALUES ('viewer',?,'user')").run(hash);const agent=request.agent(app);const s=await agent.get('/api/auth/session');const login=await agent.post('/api/auth/login').send({username:'viewer',password:'ordinary-user-password'}).expect(200);await agent.get('/api/admin/users').expect(403);expect(login.body.user.role).toBe('user')});
 it('never returns password hashes',async()=>{const agent=request.agent(app);await agent.get('/api/auth/session');const login=await agent.post('/api/auth/login').send({username:'admin',password:'a-secure-test-password'});const csrf=login.body.csrfToken;const users=await agent.get('/api/admin/users').expect(200);expect(users.body.every((u:any)=>!('password_hash'in u))).toBe(true);await agent.post('/api/auth/logout').set('X-CSRF-Token',csrf).expect(204)});
 it('requires CSRF for authenticated mutations',async()=>{const agent=request.agent(app);await agent.get('/api/auth/session');await agent.post('/api/auth/login').send({username:'admin',password:'a-secure-test-password'});await agent.post('/api/auth/logout').expect(403)});
 it('loads a complete working demo dataset through the admin API',async()=>{const agent=request.agent(app);await agent.get('/api/auth/session');const login=await agent.post('/api/auth/login').send({username:'admin',password:'a-secure-test-password'}).expect(200);const loaded=await agent.post('/api/admin/database-sources/load-demo').set('X-CSRF-Token',login.body.csrfToken).expect(201);expect(loaded.body.crossValidation.status).toBe('complete');const brands=await agent.get('/api/valves/brands').expect(200);expect(brands.body).toEqual(['Meridian','Northstar'])});
 it('supports browser-based first-run administrator setup',async()=>{appDb.transaction(()=>{appDb.prepare('DELETE FROM audit_logs').run();appDb.prepare('DELETE FROM database_sources').run();appDb.prepare('DELETE FROM sessions').run();appDb.prepare('DELETE FROM users').run()})();const agent=request.agent(app);const session=await agent.get('/api/auth/session').expect(200);expect((await agent.get('/api/auth/setup-status')).body.required).toBe(true);const setup=await agent.post('/api/auth/setup').set('X-CSRF-Token',session.body.csrfToken).send({username:'first-admin',password:'first-admin-password'}).expect(201);expect(setup.body.user).toMatchObject({username:'first-admin',role:'admin'});expect((await agent.get('/api/auth/setup-status')).body.required).toBe(false)});
});
